package models

const (
	TypeErrorResponse    = "error"
	TypeSuccessResponse  = "success"
	TypeBannedResponse   = "banned"
	TypeAuthResponse     = "auth"
	TypeAdmin            = "admin"
	TypeMerchant         = "merchant"
	TypeUser             = "user"
	TypeAllAdmins        = "all_admins"
	TypeAllCoupons       = "all_coupons"
	TypeAllAttributes    = "all_attributes"
	TypeAllCategories    = "all_categories"
	TypeAllWallets       = "all_wallets"
	TypeUserCart         = "user_cart"
	PlatformMobile       = "mobile"
	PlatformWeb          = "web"
	SignTypeNative       = "native"
	SignTypeParty        = "party"
	MerchantStatusActive = "active"
	MerchantStatusBanned = "banned"
	UserStatusActive     = "active"
	UserStatusBanned     = "banned"
	ItemStatusActive     = "active"
	CouponTypeFixed      = "fixed"
	CouponTypePercentage = "percentage"
)
